language: rust
rust:
- stable
matrix:
  include:
  - os: osx
    env:
    - NAME=cidr-to-iplist
    - TARGET=x86_64-apple-darwin
    - PACKAGE=cidr-to-iplist-macos.tgz
  - os: linux
    env:
    - NAME=cidr-to-iplist
    - TARGET=x86_64-unknown-linux-gnu
    - PACKAGE=cidr-to-iplist-linux.tgz
  - os: windows
    env:
    - NAME=cidr-to-iplist
    - TARGET=x86_64-pc-windows-msvc
    - PACKAGE=cidr-to-iplist-windows.tgz
cache: cargo
script:
- cargo build --target $TARGET --verbose --release
- cargo test --target $TARGET --verbose --release
- ls -al target/$TARGET/release/
before_deploy:
- tar -czf $PACKAGE -C target/$TARGET/release/ $NAME
deploy:
  provider: releases
  api_key:
    secure: OZSCgjjhHtezJVnLmb2D2Dt/iI8oqJBF3bieSHGdTFMl7G/lK1oHgu+wKvp+MoJnhPkI9bduPeVMDdI+3A2K0eI7vhriCgqTj996akDbU0kvIb5DcrQftCNFRxzdDBTKpE8LFYEx4+IR1NVapAc/apU7obtJim+UPQwWiQH7aJGN5zx5wHsG9kK13s6gmNkSOLho5GwrS2R/DhRIeGbhyApmEJtHI+08QrPFELXiq1RsmMjhLolUK1bJJyHzGt8lef+Gonw05PYmsP8ZzIwnr9NejrDfN1lSVL60ay3xKRKe17BUS9wJkyc2TBKCyXTmf0QITGuTE1BYjxkSBwh6dv2VHhtLx4JYsMS3YZuIwmOS2KHjHN73mZS3pgoRndb+OdV8/xTfe+LwWB6A0t2/Ba5wUv4+a7V6DlOcBJKPGYvVUplx7QTAzPWrRxLwwr2k6GeV2ejUjGj9TQHPw9TWIJ9cFKCP09zyo17/hI0ubTIq3uoCzLALQ5XWOajh4tT6i6Ed8Xh0CKNI4/fuMFdWVTtqTPIPezH8YjtI0SVwfja0LRBom5rcuBu1v+t7Luyh5R9AYri6td5jyGsd/1ww1vfMJ/yutOKf3YxDZM0BN5t0jfOARS1iegTs6taJ/Tfu9/qB0N58J+5uCcv/9IMXOAXOazmvLW6ZlkfjScK++n0=
  file: ${PACKAGE}
  skip_cleanup: true
  draft: false # set this to true if you want to have drafts
  on:
    repo: tanis2000/cidr-to-iplist
    tags: true # set this to false to create a new build at every push